- code/Helper/Data.php
- code/Model/Mysql4/Fulltext/Collection.php
- code/Model/Resource/Fulltext.php
- code/Model/Resource/Fulltext/Collection.php
- code/etc/config.xml
- code/etc/system.xml
Resubmitted on a separate branch and rebased on master:
Magento is designed to save the results of a query into the catalogsearch_result table, but these results get cleared so frequently and the use of this table creates so much additional lock contention and Algolia is so fast that this method really doesn't make sense. This pull request causes the default behavior to bypass the use of this table which actually makes loading the results page much faster and reduces database load and most importantly, lock contention with other important things like submitting orders.
> Improve lock contention with "Use Result Cache" option.

- code/Helper/Data.php
Injected data by a listener to the algolia_product_index_before event were not used is the method.
The price should be sent as float to ensure Algolia engine is using it as a numerical value for ranges & sliders.
> Fix getProductJSON for listener's data and price type

- code/Model/Resource/Fulltext.php
Using `$this->_getWriteAdapter()` to grab a table name does not work for Magento installs that have prefixed MySQL tables (specified in `app/etc/local.xml`, under the node `config > global > resources > db > table_prefix`). To correctly retrieve the table's name, we need to go through the Magento DB singleton, which has more knowledge about Magento's internals and returns the correct, prefixed, table name.
All other uses of `$this->getWriteAdapter()` in the file seem to be fine since they aren't used to grab table names.
> Support Magento installs that use prefixed MySQL tables

- code/Model/Queue.php
$pid is a string type here so is_int will never return true. I believe the original intention was to use is_numeric to ensure $pid was a number, regardless of data type.
> changed is_int to is_numeric on pid job retry check

- code/Helper/Data.php
Old product collection filtering method only retrieved products with visibility "catalog, search". Products with visibility "search" were not being included for whatever reason. Filtering the product collection this other way will instead get products with visibility "search" or "catalog, search".
> changed how product filter gets products with visiblity search or catalog, search

- code/Block/System/Config/Form/Field/Customrankingcategory.php
- code/Block/System/Config/Form/Field/Customrankingproduct.php
- code/Block/System/Config/Form/Field/Customsortordercategory.php
- code/Block/System/Config/Form/Field/Customsortorderproduct.php
- code/Block/System/Config/Form/Field/Facets.php
- code/Block/System/Config/Form/Field/Sorts.php
- code/Helper/Algoliahelper.php
- code/Helper/Config.php
- code/Helper/Data.php
- code/Helper/Entity/Helper.php
- code/Helper/Entity/Producthelper.php
- code/Model/Indexer/Algolia.php
- code/Model/Observer.php
- code/Model/Queue.php
- code/Model/Resource/Engine.php
- code/Model/Resource/Fulltext/Collection.php
- design/frontend/template/topsearch.phtml
Looks like v1.2.0 is loading helper classes directly by name as opposed to using Magento's helper loader, preventing extension of the Algolia helper classes without some tedious modifying of several classes.
`$this->product_helper   = new Algolia_Algoliasearch_Helper_Entity_Producthelper();`
vs
`$this->product_helper   = Mage::helper('algoliasearch/entity_producthelper');`
Also, changed a few more private variables to protected.
> Loading helper classes via magento helper loader

- code/Helper/Entity/Producthelper.php
Adds a new event to allow observers to extract additional data from the
collection of sub products and add to the index. This can be used for
example, to add images URLs of child products that can later be used for
alternative images
> Event to add additional data for child products

- code/Helper/Entity/Producthelper.php
Fixed a bug where having the Mage_Review-module disabled caused the indexing not to run.
Added a simple check for this. Runs without problems now.
> Disabling the Mage_Review-module caused the indexing not to run

- code/Helper/Entity/Producthelper.php
If the configurable, bundles or grouped products doesn't have any sub products. The $ids variable ends up beeing empty. This will result that the getProductCollectionQuery will return the whole product catalog as sub_products.
> Handling configurable, bundles and grouped products without options

- code/Helper/Entity/Producthelper.php
It seems like fetching a collection with an empty category array results in a a bad sql on at least Magento 1.9.0.1 
To avoid this we check if the product has any category ids attached to it and only doing the category collection if there is at least one category attached to the product.
> Do not do a query for categories if the product don't have any

- code/Helper/Entity/Producthelper.php
This will only index the categories under the current category for each store.
If you have several category trees for each store, and have the same products in multiple category trees this patch will prevent that all categories trees are indexed for each store. This will only index the categories that derive from the root category for the current store.
> Only add categories under the current root category

- code/Helper/Entity/Producthelper.php
The Configurable product in Magento (or even grouped products) does not update the stockitem  automaticly when all the children is out of stock.
The check on line 588 will always be true as long as the status on the configurable product is set to "in stock":
$customData['in_stock'] = (int) $stockItem->getIsInStock();
Since Algolia is using this to see if the product is sellable or not, the configurable product should be set out of stock if all the sub products is out of stock.
> Set configurable product out of stock, if all the children is out of stock.

- code/Helper/Entity/Producthelper.php
- code/Model/Indexer/Algolia.php
See comments on code for fix for #273. This uses Magento method calls instead of relying on hard-coded values which could change (or expected behavior of values could change. Using the method calls should have Algolia behave the way the user would expect it to based on native Magento behaviors)
> Changed code to use Magento method calls instead of hard coded values

- code/Helper/Entity/Producthelper.php
Fix for #277.  NOTE: This should be done as a hotifx release since the current code will make it so that all products generate a 404 from search or categories when using Algolia.
> Fix for product URLs

- design/frontend/template/topsearch.phtml
$group_id is not set anywhere so it throws an error in the template file when customer groups are enabled
> Fix missing group_id variable

- code/Helper/Config.php
- code/Helper/Logger.php
- code/etc/config.xml
- code/etc/system.xml
Added setting to allow disabling logging (and disable it by default) to avoid creating a large algolia.log file.  This is needed as the main logging setting might be enabled but merchant will not want (or need) this log enabled
> Add config setting to control logging

- code/Helper/Config.php
Many stores use square images, and only pass the width to the resize fucntion. The second param is then set to 'null' by default.
To be able to use the same images in Algolia, you'd like to only pass the width there too.
However, in the Magento config, if you're leaving a field empty, the value is an empty string, not null.
So, if you're for example setting the width to 400 and leaving the height value empty in the Algolia config, the values passed is resize(400, '').
This only works if the image is already cached, since magento does a file_exists on the 'would-be-cached' image's filepath, where the filepath is a string, and putting null or '' in a string is practically the same thing.
But - when it is not cached, and Magento tries to resize, it does a strict compare with null, and then …
> If a config value for image size is empty, return null

- code/Helper/Entity/Additionalsectionshelper.php
getColumnValues() for multiselect attributes returns ids imploded by comma.
Each row should be exploded. If not,final array contains much duplication.
> multiselect array unique

- code/Helper/Entity/Producthelper.php
When customer groups are enabled slaves were only being set for price sorts not other sorts that were set such as price, rating etc.
> Set product slaves for all sorting indices when customer groups are enabled

- code/Helper/Entity/Additionalsectionshelper.php
When adding additional sections like brands some attributes are shown that are only against products that are disabled so will never have any results in the search
> Only get attributes for products that are enabled

- code/Helper/Entity/Helper.php
Remove magento specific syntax from indexed pages. When searching for "black..." in the autocomplete dropdown it was showing {{block type="core/template" template="page/html... below the page's name.
> Strip magento block directives

- code/Helper/Config.php
- code/Helper/Entity/Pagehelper.php
- code/etc/config.xml
- code/etc/system.xml
- When indexing CMS pages, this module will render template directives by default instead of simply stripping them out.
- Adds a configuration option to the Admin Panel which allows the user to change this behavior, if desired.
Admin Panel:
> CMS content: template directives

- code/Model/Resource/Engine.php
It should fix the bug when you build dev container for the first time and index settings are not set.
_Not sure if we want to call saveSettings everytime when rebuilding products, but I don't know where to put it besides creating a new indexer._
> Save index settings on full products rebuild

- design/adminhtml/layout/algoliasearch.xml
- design/frontend/layout/algoliasearch.xml
Not sure if we can use the same block's name (`algolia-beforebodyend`) both in admin and frontend?
> Set names to layouts' blocks. Fixes #378

- code/Model/Indexer/Abstract.php
- code/Model/Indexer/Algolia.php
- code/Model/Indexer/Algoliacategories.php
This change enables the Algolia extension for Magento to now automatically update the product index when a product is added to or removed from a category via the "Manage Categories" menu.
This change also moves some duplicate code into a helper class.
> Update product index if category products updated

- code/Helper/Entity/Additionalsectionshelper.php
- code/Helper/Entity/Producthelper.php
When I tried to index attribute `category_ids` it failed because it tried to fetch textual value of attribute. But the attribute was already set. There was probably logical error in condition.
Could you please review as I'm not sure it's not harmful. I tested it a bit and seems to work OK.
> Fix already set elements indexing

- code/Helper/Config.php
- code/Helper/Data.php
- code/Helper/Entity/Categoryhelper.php
- code/Helper/Entity/Helper.php
- code/Helper/Entity/Producthelper.php
- code/Model/Indexer/Abstract.php
- code/Model/Indexer/Algolia.php
- code/Model/Observer.php
- code/Model/Queue.php
- code/Model/Resource/Engine.php
- code/etc/system.xml
Implements #424 
- works everytime
- no specific configuration needed
- keeps indices in consistent state
- simplifies code
- makes queue more effective, because there is no need to add `removeProducts` to queue table. So only merged `rebuildProducts` tasks are processed.
> Simpler products removing

- design/frontend/template/instantsearch.phtml
@maxiloc It was caused because instant search was no started. I strart it everytime now and works. I tested all the combinationas turned on/off autocomplete / instant search and it works OK. Did I miss some use case or can we leave it like that?
> Fix showing instant search bars on products' details

- code/Helper/Entity/Producthelper.php
In some setups, like when catalog prices are maintained excl. tax and displayed in the store with tax, the price still get indexed without tax, even when $with_tax returns true here (Helper/Entity/Producthelper.php, line 315):
$price = (double) Mage::helper('tax')->getPrice($product, $product->getPrice(), $with_tax, ...
This seems to be due to that the tax helper's getPrice function tries to get the tax percant / tax class from $product, but $product doesn't include that, returns NULL, and no tax is added.
This fixes that by including the tax class id in the product collection.
> Prices being indexed excl.tax instead of incl.tax in some tax setups

- js/algoliasearch/internals/frontend/common.js
We had this problem when manufacturer attribute contained "+" or "&" characters, in this case in suggestion list the url is not escaped leading to special symbols being dropped and no results are returned, specially with "&" only symbols before are used for search. Yet after this change the selected filters have the ampersand double escaped, but at least there are results for the search
> Encode attribute values

- app/design/frontend/base/default/template/algoliasearch/instantsearch/hit.phtml
- js/algoliasearch/instantsearch.js
Following on from issue #322 this patch updates the hit widget to use the
allItems template. It updates hit.phtml with the {{hits}} tags so that it
continues to work as before.
The diff on hit.phtml is a lot more readable if you diff with -b
> Hits widget: Use allItems template not item

- app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
Fixes #526 
Really not sure about the approach. Any feedback appreciated.
> Don't include some bundled products' attributes within its' master product

- app/code/community/Algolia/Algoliasearch/sql/algoliasearch_setup/mysql4-upgrade-1.6.0-1.7.1.php
Hello,
The `data` column of the queue table (`algoliasearch_queue`) is a `VARCHAR(5000)` so if you reindex more than 1000 products for example, it will cut the json and make it invalid.
This PR updates the type to `TEXT`.
> Change algolia queue data column type to TEXT

- app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/ProductAdditionalAttributes.php
This one was missed when restoring PHP 5.3 compatibility (causes a fatal error in the Magento configuration area)
> PHP 5.3 compatibility fix

- app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
When a bundle product does have a special price the old price isn't shown. This is because the `price_type` attribute isn't selected, see: https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Bundle/Model/Product/Price.php#L69-L76
> Fix to show correct bundle product prices

- app/code/community/Algolia/Algoliasearch/Helper/Entity/Additionalsectionshelper.php
- app/code/community/Algolia/Algoliasearch/Helper/Entity/Pagehelper.php
- app/code/community/Algolia/Algoliasearch/Helper/Entity/Suggestionhelper.php
In general it's better for relevancy.
> Set hardcoded searchable attributes as unordered.

- app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext/Collection.php
When Algolia is disabled with `algoliasearch/credentials/enable_backend` for a store it's not returning any search results.
> Bugfix, no search results when Algolia is disabled

- app/design/frontend/base/default/template/algoliasearch/autocomplete/attribute.phtml
- app/design/frontend/base/default/template/algoliasearch/autocomplete/category.phtml
- app/design/frontend/base/default/template/algoliasearch/autocomplete/page.phtml
- app/design/frontend/base/default/template/algoliasearch/autocomplete/suggestion.phtml
- app/design/frontend/base/default/template/algoliasearch/instantsearch/hit.phtml
- app/design/frontend/base/default/template/algoliasearch/instantsearch/wrapper.phtml
- skin/frontend/base/default/algoliasearch/algoliasearch.css
> Define clearfix CSS class

- app/code/community/Algolia/Algoliasearch/Helper/Config.php
- app/code/community/Algolia/Algoliasearch/etc/system.xml
- dev/bin/test.sh
- dev/runTests.sh
- tests/AbstractIndexingTestCase.php
- tests/AbstractTestCase.php
- tests/CategoriesIndexingTest.php
- tests/ConfigTest.php
- tests/PagesIndexingTest.php
- tests/ProductsIndexingTest.php
- tests/QueueTest.php
- tests/bootstrap.php
This means that if you turn off indexing, for whatever reasons, your can still search them on your frontend.
I think it's better to not delete the indices when the indexing option is turned off because you might need to turn it off temporarily (maintenance, debugging or so) but you still want your frontend to have the Algolia search bar.
**Related:**
* Previous PR #792
* https://discourse.algolia.com/t/using-main-web-search-on-all-store-locations/697
* I added a filter option to the `runTests.sh` script so we can choose which tests to run while developing 🎉 
* Default configuration is now re-applied before each tets
> Make indexing and search options independant

- app/code/community/Algolia/Algoliasearch/Model/Indexer/Abstract.php
- app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php
The engine shouldn't be loaded via direct initialization and should instead follow Magento best practice to allow rewrites by third party developers.
> Enable Rewrite for Algolia_Algoliasearch_Model_Resource_Engine

- js/algoliasearch/instantsearch.js
> Rework of InstantSearch extensionality [BC break]

- app/code/community/Algolia/Algoliasearch/etc/config.xml
Leads to an unexpected behavior when customers are managing synonyms in dashboard and then upgrade to the new version with synonyms management, which leads to wiped out synonyms.
cc @mikaa123
> Turn off the synonyms management by default

- app/code/community/Algolia/Algoliasearch/Helper/Config.php
- app/code/community/Algolia/Algoliasearch/Model/Observer.php
- app/code/community/Algolia/Algoliasearch/etc/config.xml
- app/code/community/Algolia/Algoliasearch/etc/system.xml
- app/design/frontend/base/default/layout/algoliasearch.xml
This feature prevents category pages to be rendered on backed when they use Algolia. As a result the rendering should be much faster. Implements #877 
**TODO:**
> Prevent backend rendering

- js/algoliasearch/internals/frontend/common.js
**Summary**
When using autocomplete, this error ends up in the console:
Uncaught ReferenceError: payload is not defined
at suggestion (common.js:295)
at e (dataset.js:157)
at Object.map (jquery.js:484)
at r (dataset.js:141)
at r._render (dataset.js:105)
at t (dataset.js:202)
at Object.callback (hits.js:20)
at AlgoliaSearchCore.js:456
Refering to:
Line 295, hit.__queryID = payload.queryID;
(The js console errors were saved when using the master branch, so the line numbers is being a bit off from the PR which is for the developer branch)
**Result**
No more errors in the console! :)
> Missing payload causes js console errors

- app/code/community/Algolia/Algoliasearch/Model/Observer.php
Handle Manual mode for pages and products indexers.
Now when a user selects "manual" mode for "algolia_search_indexer" or "algolia_search_indexer_pages" indexers, the "on save" events are not propagated to Algolia anymore.
> Handle manual indexing mode for cms pages and products

- app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliadeleteproducts.php
The name is currently misleading and gives users a feeling that it'll delete inactive products from Magento DB completely. It only removed inactive products from Algolia so its' not appear in search. This commit explicitly mentions that it will remove it only from Algolia and not DB.
Fixes #1052
> Improve name of "Remove inactive products" indexer

- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Indexingqueue.php
- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Indexingqueue/Edit.php
- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Indexingqueue/Edit/Form.php
- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Indexingqueue/Grid.php
- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Indexingqueue/Grid/Renderer/Json.php
- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Indexingqueue/Status.php
- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Reindexsku/Edit.php
- app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Reindexsku/Edit/Form.php
- app/code/community/Algolia/Algoliasearch/controllers/Adminhtml/Algoliasearch/IndexingqueueController.php
- app/code/community/Algolia/Algoliasearch/controllers/Adminhtml/Algoliasearch/ReindexskuController.php
The new indexing queue admin page gives a 404 on servers that are case sensitive. These changes rename the files and classes that are affected to fix them.
Fix for issue #1095
> Rename files to fix 404 issue #1095

- app/code/community/Algolia/Algoliasearch/Helper/Config.php
- app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml
When customerGroups are enabled, and magento is configured to display prices both **with** and **without** tax, the prices with tax were not being fetched with the search results.
> Fix price_with_tax when customerGroups are enabled

- app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php
- app/code/community/Algolia/Algoliasearch/Helper/Config.php
- app/code/community/Algolia/Algoliasearch/Model/Queue.php
- app/code/community/Algolia/Algoliasearch/Model/Source/MaxRecordSize.php
- app/code/community/Algolia/Algoliasearch/etc/system.xml
- app/code/community/Algolia/Algoliasearch/sql/algoliasearch_setup/mysql4-upgrade-1.15.0-1.16.0.php
**Summary**
Reduce the number of "Record size is too big" errors by adjusting the record size according to plan through system admin and default the size to 10000. Update the retry method for stuck jobs with PIDs that have not be unassigned during system error (ie time out or max memory limits). 
**Result**
* Added max_record_size to pull limit from plan in system configuration 
* Changed the default max_record_size to 10000
* Added locked_at column to queue table and unlockStackedJobs() method to Queue model for jobs processing stuck after system error
> Add max_record_size and indexing queue PID retry method 

- js/algoliasearch/internals/frontend/common.js
**Summary**
Helpscout issue (133308) on sticky autocomplete input value after clearing via toggle. 
**Result**
Added to the clear event to clear the autocomplete input data for query to clear value.
> Fix sticky autocomplete input value after clear by toggle

- CHANGELOG.md
- README.md
- app/code/community/Algolia/Algoliasearch/etc/system.xml
- app/etc/modules/Algolia_Algoliasearch.xml
- Update max PHP dependency (#1090)
- Update Reindex SKU for improved messaging  (#1098)
- Added ProxyHelper to assist with plan upsell (#1109)
- Update autocomplete version in algoliaBundle.js (#1121)
- Improvements to Indexing and Indexing Queue
- Skip inactive stores (#1101)
- Add distinct to category collection fetch (#1104)
- Fail "Remove Algolia products" silently on non-existent index (#1111)
- Fetch max_record_size and add retry on stuck PIDs for indexing queue (#1117)
- Fix directory casing 404s (#1095)
- Add table prefixes when calling core/resource instances (#1097)
- Fix price_with_tax for customer groups (#1100)
- Fix autocomplete frontend hook (#1102)
- Fix jobs locking (#1118)
- Fix Dockerfile (#1120)
- Fix sticky autocomplete input value after clear toggle (#1122)
> Bump to 1.16.0

- app/code/community/Algolia/Algoliasearch/etc/system.xml
**Summary**
In System > Configuration > Algolia Search > Google Analytics, when you enable the configuration, it does not display the dependant fields to configure the settings. 
HS Ticket: #201666
**Result**
Updated the depends node to the correct field name that was changed when we introduced Click Analytics.
> Configuration fix Google Analytics dependent fields

- app/code/community/Algolia/Algoliasearch/Helper/Config.php
Empty result popular queries feature is in both autocomplete and in instantsearch. If instantsearch is not enabled, the method will return an empty array. 
Remove condition in \Algolia_Algoliasearch_Helper_Config::getPopularQueries() to remove instantsearch dependency.
> Fix popular queries empty result condition

- app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml
- js/algoliasearch/click_conversion_analytics.js
- js/algoliasearch/instantsearch.js
**Summary**
Insights URL was not optional and includes the URL even if cc analytics was not enabled.
**Result**
Removed unused event. Added `enabled` as a ccAnalytics parameter and added condition to the makeURL function.
> fix: Insights URL for CC Analytics only

- app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php
Based on the updated PHP Client, I've updated the `copyQueryRules()` method to use the `scopedCopyIndex`. This is the alternative for PR#1161.
> Update copyQueryRules to use scopedCopyIndex method

- app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php
We should not forward query rules to the replica indexes.
HS Ticket #268254
> Set forwardToReplicas for copy rules to false
