design/frontend/template/topsearch.phtml, skin/livesearch.js
Fixes a few minor bugs:
* When a user searches something that matches categories and then changes search which matches no categories the results may not be updated.
* Fix keypress handling: tab goes to next result instead of opens current result.
=> Javascript improvements (keypress and result rendering).

code/Helper/Data.php
Allow bypassing getThumbnailUrl and getImageUrl because they trigger
the internal GD2 resizing functions. When you store your images in
e.g. S3 bucket you don't need that resizing functions and it even
generates a lot of errors due to missing files.
ordered_qty and stock_qty can be pre-calculated differently and
efficiently so the checks here can skip the default calculation in this
module.
Overall: your code style could be improved to match it more the Magento way.
Please check file permissions. There should be no file mode 755 on any
file or 777 on directories.
=> Fix image generation and calculation of custom ordered/stock_qty

code/Helper/Entity/Producthelper.php
If Magento is set to display both prices, the current code will only export the
price without tax. This patch rewrites the handlePrice method to include prices with and without tax, when displayBoth is set.
Is this or something like it likely to be accepted? I realise this patch looks really horrible, but I refactored the handlePrice method at the same time because it was quite long and there would be a lot of duplication.
=> Upload prices with taxes again

code/Helper/Config.php, code/Helper/Entity/Producthelper.php, code/etc/config.xml
Thanks for the comments. I have moved my work to the develop branch and the lookup to the config helper.
=> Making product types mappable via configuration

design/frontend/template/beforetopsearch.phtml
Fixed issue with JS error on non undefined hit._highlightResult.categories_without_path
=> Fixed error on undefined categories_without_path

code/Helper/Algoliahelper.php, code/Helper/Data.php, code/Helper/Entity/Producthelper.php, code/Helper/Logger.php, code/Model/Indexer/Algolia.php, code/Model/Indexer/Algoliaadditionalsections.php, code/Model/Indexer/Algoliacategories.php, code/Model/Indexer/Algoliapages.php, code/Model/Indexer/Algoliaqueuerunner.php, code/Model/Indexer/Algoliasuggestions.php, code/Model/Queue.php, code/Model/Resource/Engine.php, code/Model/Resource/Fulltext.php
See https://github.com/algolia/algoliasearch-magento/pull/287 targeting develop branch this time instead of master
=> Use protected instead of private for methods and fields

doc/documentation.md
=> Updated typo in Customization section

design/frontend/template/topsearch.phtml
This change fixes some derp spelling.
=> Fix typos in topsearch.phtml

code/Helper/Entity/Producthelper.php
This change allows us to better customise which attributes we want to exclude.
=> Excluded attributes array now separate function

code/Helper/Entity/Additionalsectionshelper.php
Current store_id var seems to be usefull in this event.
=> store_id value in algolia_additional_section_item_index_before event

code/Helper/Entity/Producthelper.php
Add a comment to explain a somewhat big and hard to understand `if`.
=> Explain parent products fetching values from child products

code/Helper/Entity/Producthelper.php
=> Fix SKU indexing in simple products

code/Helper/Algoliahelper.php, code/Helper/Config.php, code/Helper/Data.php, code/Helper/Entity/Additionalsectionshelper.php, design/adminhtml/template/adminjs.phtml, design/frontend/template/autocomplete.phtml, design/frontend/template/instantsearch.phtml, design/frontend/template/internals/commonjs.phtml, js/admin_scripts.js
- Refactored retrieval of extension's version - now it's fetched from the unified extension's XML config
- Added correct version to frontend API calls
- Added annotations to `commonjs.phtml` template variables
=> Refactor versioning

code/Helper/Entity/Pagehelper.php
=> Fix pages indexing - pages were indexed in stores where they do ... 

design/frontend/template/internals/commonjs.phtml
Fixes #338 
Tested on Modern IE Win7 IE9
=> Fix undefined algoliaConfig JS var

design/frontend/template/autocomplete.phtml, design/frontend/template/instantsearch.phtml, design/frontend/template/internals/commonjs.phtml
I changed skin static files path to use Magento method `$this->getSkinUrl()`.
It's the proper way to call static files.
=> [~TASK] Remove absolute skin path on template files

code/Helper/Data.php
I know it will produced big data, but it might be useful for debugging. WDYT @maxiloc?
Implements #426
=> Log updated and deleted IDs

design/frontend/template/internals/commonjs.phtml
=> Fix content restoration on cross click

design/frontend/template/instantsearch/hit.phtml
=> Fix duplicate CSS classes

code/Helper/Algoliahelper.php
Those are the information we ask in 90% of support tickets.
Dashboard and other system will have no problem with the UA format, checked.
=> Send more information in UA

code/Helper/Entity/Categoryhelper.php, code/Helper/Entity/Producthelper.php, code/Helper/Image.php, design/frontend/template/autocomplete/category.phtml, design/frontend/template/autocomplete/product.phtml, design/frontend/template/instantsearch/hit.phtml
=> Fix the issue with CDN images

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
=> Fix array_unique notices

app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/ProductAdditionalAttributes.php, app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php, app/code/community/Algolia/Algoliasearch/etc/system.xml
See the previous PR: https://github.com/algolia/algoliasearch-magento/pull/548
=> Added a index empty value option on indexed attributes

js/algoliasearch/instantsearch.js, skin/frontend/base/default/algoliasearch/algoliasearch.css
=> Hide IS page info panel on no results

app/code/community/Algolia/Algoliasearch/Helper/Entity/Suggestionhelper.php
Improves relevancy.
Implements #568
=> removeWordsIfNoResults on suggestion index set to lastWords

js/algoliasearch/internals/adminhtml/admin_scripts.js
+ Added small line with rate request
Fixes #544
=> Less aggressive "new version" message

skin/frontend/base/default/algoliasearch/algoliasearch.css
=> Prefix vague CSS selectors and remove unused styles

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml, js/algoliasearch/internals/adminhtml/admin_scripts.js
=> Add option to disable synonyms management in Magento

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
Adds more relevancy options in category listings with Algolia
Implements #532
=> Index hierarchical categories without path in new main_categories attribute

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml, app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml
Implements #533 
Breaks hierachical widget of IS page. It's mentioned in comment of configuration input.
=> Add option to choose where index or not the whole category tree of the product

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml, app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml, js/algoliasearch/internals/frontend/common.js, skin/frontend/base/default/algoliasearch/algoliasearch.css
Implements #551
... and fixes suggestions styles in autocomplete dropdown menu.
=> Add option to disable displaying categories with popular queries

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Model/Indexer/Abstract.php, app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliacategories.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml
=> Add option to reindex all category's products

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
=> Improved removing of "No" values

js/algoliasearch/autocomplete.js
=> Enable selecting autocomplete menu items

app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php, app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php
Now it correctly detects enabled queue and do not perform delete operations.
=> Fix reindexation when using full reindex of all ("catalogsearch_fulltext")

app/code/community/Algolia/Algoliasearch/Model/Indexer/Abstract.php
=> Fix fatal error on product delete where method was called on non-existing object

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
**Fix for:**
`PHP Notice:  Undefined index: index_no_value in algoliasearch-magento/code/Helper/Entity/Producthelper.php on line 985`
=> Fixed undefined index notice

app/code/community/Algolia/Algoliasearch/etc/system.xml, js/algoliasearch/autocomplete.js
Something like that @JanPetr?
Fix #701
=> Ability to hide categories & products from dropdown menu

js/algoliasearch/instantsearch.js
=> Show refined category on replaced category page with IS

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Helper/Data.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php, app/code/community/Algolia/Algoliasearch/Model/System/IndexVisibility.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml
=> Add option to index only products with specific visibility

app/code/community/Algolia/Algoliasearch/Helper/Entity/Categoryhelper.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Pagehelper.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Suggestionhelper.php
=> Pass entityObject into a custom events called in getObject methods

js/algoliasearch/internals/frontend/common.js
=> Fix IS page clearance

js/algoliasearch/instantsearch.js
=> Fix category refinement

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/bin/dump.php
=> Implement debug dump script

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
Adds weee tax (European tax on electronic products) to the price
see #813
=> Add weee tax to product price

js/algoliasearch/internals/adminhtml/admin_scripts.js
=> Replace hardcoded "admin" URL with a dynamic one

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml, app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml, js/algoliasearch/autocomplete.js
=> Add option to turn on autocomplete menu's debug option from configuration

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
=> Fix store specific facets

app/code/community/Algolia/Algoliasearch/Model/Indexer/Algolia.php, app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliaadditionalsections.php, app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliacategories.php, app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliapages.php, app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliaqueuerunner.php, app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliasuggestions.php, app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php
=> Don't run reindex when module output is disabled

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml, app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml, js/algoliasearch/instantsearch.js, js/algoliasearch/internals/frontend/common.js
=> Show correct image for color specified by facet or query

app/code/community/Algolia/Algoliasearch/Helper/Data.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Pagehelper.php, app/code/community/Algolia/Algoliasearch/Model/Observer.php, app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php, app/code/community/Algolia/Algoliasearch/etc/config.xml
=> Reindex CMS page immediately after it was updated

app/code/community/Algolia/Algoliasearch/sql/algoliasearch_setup/mysql4-upgrade-1.11.1-1.12.0.php
=> Fix 1.11.1 migration

app/code/community/Algolia/Algoliasearch/Model/Observer.php, app/design/frontend/base/default/layout/algoliasearch.xml
=> Don't render unnecessary templates and JS

app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Notifications.php, app/code/community/Algolia/Algoliasearch/etc/system.xml, app/design/adminhtml/default/default/template/algoliasearch/notifications.phtml, js/algoliasearch/internals/adminhtml/admin_scripts.js
=> Change queue doc links and remove queue notif if queue is empty

app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php
=> Pages encoding fix

js/algoliasearch/autocomplete.js
Fixes #902 
@sam327, could you give it a try if it fixes your issue?
=> Handle buggy onclick event on iOS

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Model/Observer.php, app/code/community/Algolia/Algoliasearch/Model/System/BackendRenderingDisplayMode.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml
=> Don't prevent backend rendering on static content only categories

app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml, app/design/frontend/base/default/template/algoliasearch/instantsearch/hit-item.phtml, app/design/frontend/base/default/template/algoliasearch/instantsearch/hit.phtml, app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml, js/algoliasearch/instantsearch.js, skin/frontend/base/default/algoliasearch/algoliasearch.css
If you turn the option on, you'll see a _load more_ button instead of the traditional pagination.
Any comments are welcome while I'm adding tests.
=> Add infinite scroll feature

app/code/community/Algolia/Algoliasearch/Model/Observer.php, app/design/frontend/base/default/layout/algoliasearch.xml, app/design/frontend/base/default/template/algoliasearch/autocomplete.phtml
=> Optimize templates loading

app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php
Fixes #890
@royduin, would you find some time to give it a try? I'd be really helpful! Thanks!
=> Reindex Magento fulltext correctly for stores which has Algolia disabled

dev/bin/algoliasearch.xml
=> Include admin skin files

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
=> Select only unique products on reindex

app/code/community/Algolia/Algoliasearch/controllers/Adminhtml/AlgoliaQueueController.php, js/algoliasearch/internals/adminhtml/admin_scripts.js
We already have a QueueController in our project so that one is overwritten by Algolia, a prefix fixes this.
=> Update and rename QueueController.php to AlgoliaQueueController.php

app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml, js/algoliasearch/internals/frontend/common.js
=> Fix expired special prices

app/code/community/Algolia/Algoliasearch/Model/Observer.php
=> CMS page observer: prevent rebuild during fresh install

CHANGELOG.md, README.md, app/code/community/Algolia/Algoliasearch/etc/config.xml, app/code/community/Algolia/Algoliasearch/etc/system.xml, app/etc/modules/Algolia_Algoliasearch.xml
=> Bump to 1.14.0

app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml
=> Fix use of short array syntax

app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml, js/algoliasearch/instantsearch.js, skin/frontend/base/default/algoliasearch/algoliasearch.css
=> Format price on slider facets

app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/ProductAttributes.php, app/code/community/Algolia/Algoliasearch/Helper/Config.php, app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php, app/code/community/Algolia/Algoliasearch/etc/system.xml
Add non castable textfield attributes advanced feature
=> Add non castable textfield attributes advanced feature

app/code/community/Algolia/Algoliasearch/Block/Adminhtml/Notifications.php, app/design/adminhtml/default/default/template/algoliasearch/notifications.phtml
**Summary**
No linked issues, just refactoring for best practices. Keeping logic out of the template files and into the appropriate block class method _toHtml(). Updated getQueueInfo() method to cache value. 
**Result**
No changes in UI. Adminhtml Notifications should appear only with the appropriate conditions otherwise return empty string.
=> Refactoring Notifications Block / Template

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
=> Exclude non-salable subproducts from price calculation

dev/runTests.sh
👋 
Saw some light, got in, and then found this typo 👀 
I know how Algolia is tolerant to this but I figured a fix was in order anyway 😉
=> Fixes typo in dev script

js/algoliasearch/autocomplete.js, js/algoliasearch/internals/frontend/common.js
=> Fix autocomplete front-end hook

app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php
=> Skip inactive stores when deleting products

app/code/community/Algolia/Algoliasearch/controllers/Adminhtml/Algoliasearch/ReindexSkuController.php
**Summary**
[[MAG-68]](https://algolia.atlassian.net/browse/MAG-68) Improve Reindex SKU form to show detailed name and qualifications for try/catch/continue 
**Result**
- Improved try/catches to allow some storeviews to continue when one of them doesn't qualify
- Updated store name to show from which website/store group/store view 
- Updated global attributes to not include store since it is not neccessary.
=> Update Reindex SKU Form

tests/QueueTest.php
Added locked_at parameter to job assert tests to match new columns
=> Update job assert test for new column locked_at

lib/AlgoliaSearch/Analytics.php, lib/AlgoliaSearch/Client.php, lib/AlgoliaSearch/ClientContext.php, lib/AlgoliaSearch/Index.php, lib/AlgoliaSearch/IndexBrowser.php, lib/AlgoliaSearch/Iterators/AlgoliaIterator.php, lib/AlgoliaSearch/Iterators/RuleIterator.php, lib/AlgoliaSearch/Iterators/SynonymIterator.php, lib/AlgoliaSearch/PlacesIndex.php, lib/AlgoliaSearch/Version.php, lib/AlgoliaSearch/loader.php
Updating Algolia PHP Client library from 1.19.0 -> 1.28.0.
=> Update PHP Client to v 1.28.0
